### ISSUE TITLE
Pesky Checkbox Appearing on Salsa forms

### ISSUE THREAD

**Issue by smadoori** [BusProject/SalsaPress#24]
Hello - I have a problem that I hope I can get help to address.

We are building a new website on Wordpress and one of our goal is to integrate Salsa throughout to better get individuals involved in our organization using the SalsaPress plugin. We've noticed a strange error that's happening with our forms (see screenshot), on the homepage, bottom left corner we have a Salsa form for sign-up. We've had this random 'required' checkbox appear out of nowhere, when our forms don't have them in Salsa.

We also noticed this error that appearing near the Salsapress icon in blog posts during drafting mode right above the WYSWYG: Warning: _() expects exactly 1 parameter, 2 given in /home/bgriffith/hivpja/src/wp-content/plugins/salsa-press/admin/embed.php on line 7

I also attached a screenshot to illustrate an example of what we are seeing on website.

We wondering anyone had any insight or possibly help us resolve this problem? We are trying to launch this site soon and really need to resolve this ASAP. Any help is greatly appreciated.
![screen shot of form](https://f.cloud.github.com/assets/6224914/1784759/02b1cdf8-68d8-11e3-99ee-297f03572df9.jpg)

**Comment by mojowen** [comment]
I think I fixed this, yes? no? maybe?

**Comment by imaginautdesigns** [comment]
This was over a year ago …… I think so?

It was on a client’s site and they’ve changed the way they were using the forms …. so I think it all worked out.   *shrug*   :-D

Chris Stuart  |  Imaginaut Designs  |  417-224-7491  |  imaginautdesigns.com

**Comment by mojowen** [comment]
I'm going to call it a win

**Comment by smadoori** [comment]
Scott – yep, the fix worked awhile ago and we were able to address the aberrant check box that was appearing in our embedded forms – thanks so much!

-Suraj
