### ISSUE TITLE
Groups not refreshing on forms

### ISSUE THREAD

**Issue by saalblade** [BusProject/SalsaPress#39]
We edited some optional groups on a Salsa sign-up form and the revisions are not appearing on the embedded form. Would you mind checking this out? I've attached screenshots of the Salsa admin vs. front-end public page.

![image](https://cloud.githubusercontent.com/assets/8781051/4274445/1d6faa0c-3cf4-11e4-9c9c-c90087ae3bec.png)
![image](https://cloud.githubusercontent.com/assets/8781051/4274449/255ef344-3cf4-11e4-997b-b66a3f5d98a0.png)

**Comment by mojowen** [comment]
No response - closin
