### ISSUE TITLE
SalsaPress not authenticating

### ISSUE THREAD

**Issue by sarah97302** [BusProject/SalsaPress#44]
Hi. After working fine for several years, the plugin started failing to authenticate a few weeks ago. I have tried changing the account i'm using to log in (we have several admin accounts), and have verified that the username and password work to log into the salsa dashboard, but i'm still getting the error message "Login Status: FAIL! :I" on the 'Set up your Salsa Connection' page.

I followed all the instructions suggested in Issue #27, and when i browse to http://action.autisticadvocacy.org/api/authenticate.sjs?email=**myemail**&password=**mypassword**, i get the following error message:

<data>
<error>Invalid login, please try again.</error>
</data>

same result if i use hq.salsalabs.com instead of our custom domain at the beginning of the url. i have tried this with several different admin accounts, and all three accounts can log in to the salsa dashboard without a problem but won't authenticate in salsapress.

any ideas for next steps?

thanks

**Comment by mojowen** [comment]
Have you contacted Salsa support? Sounds like it's an issue on their end, unfortunately.

**Comment by mojowen** [comment]
No response - closin
