### ISSUE TITLE
Zip Code Not Being Marked As Required

### ISSUE THREAD

**Issue by mojowen** [BusProject/SalsaPress#46]
From https://wordpress.org/support/topic/zip-code-should-be-required-but-is-not?replies=1#post-6858204

Our forms are set up to have "Zip Code" as a required field via the Salsa Dashboard, however when the forms are embedded via the WYSIWYG embed feature, they Zip code is never required, it does not show the * and users can successfully submit the form without entering anything in this field.

The only way I was able to get around this in the past was to use the "text" WordPress editor and manually embed an iframe with the actual Salsa form linked inside it.

Thanks in advance.

**Comment by AmandaCousins** [comment]
Hi Scott, 

Sorry to bother you, I know you're not actively supporting this project, but I'd be very grateful if you have a minute. 

I'm finally into creating a sign up form on a page, and the plugin is working flawlessly, except for the required zip. Strangely, we've had a sign up widget on the homepage for three months, and either this is a new issue with the update, or we didn't notice... lol.

So, I'm checking with Salsa to see if there may be an api issue, but I was wondering if theres a way to code the required zip into the js file. It appears there is required validation for the email field? Sorry I'm not an js expert yet  ;)

---------------------------------------------
else if ( (typeof data.messages == 'undefined' ? '' : data.messages.toString() ).match(/Please enter a valid email address/).length > 0 ) {
							self.find('label.required').addClass('oops');
							self.find('input[name=Email]').parent().find('label').addClass('oops');
							self.find('input[type=submit]').attr('disabled',false).val(objectL10n.click_to_try_again);
							self.notice( objectL10n.please_enter_valid_email_address )
						}
---------------------------------------------

Will update you if I find anything relevant from Salsa. 

Thanks in advance, 

Best,
Amanda

PS Salsa really needs to support this project. Do I need to make a petition? ;)

**Comment by mojowen** [comment]
348a552e5dea1d80244b46fe919ee56cb71b6cf7 should have fixed this 

![image](https://cloud.githubusercontent.com/assets/700444/11384455/ca44e1c6-92c4-11e5-86ef-b56cd90126c5.png)

Turns out I do have access to my old Salsa sandbox account!

As for Salsa support - would love for someone to adopt the plugin or sponsor additional development (like [Kampaweb](http://www.kampaweb.ch/de) did).

Happy to give access to the repo and plugin for any intrepid devs to work on and improve.
