### ISSUE TITLE
Salsa form not showing up

### ISSUE THREAD

**Issue by davidglenrobinson** [BusProject/SalsaPress#47]
Hello. I'm trying to get a Salsa form to show up. My client recently switch to a new Salsa account. This worked before so I'm not sure if I'm doing something wrong or it's something on the Salsa side. 

I'm able to see form I want in the Salsa Press plugin. 
![screen shot 2015-04-29 at 5 56 36 pm](https://cloud.githubusercontent.com/assets/9845722/7402451/faf4eac0-ee99-11e4-9b0d-a6981d084d98.png)

After I select the form, "Connect!", I see code inserted for a graphic rather than the from. The graphic below shows the code that worked before, and the recently inserted code. 
![screen shot 2015-04-29 at 5 58 54 pm](https://cloud.githubusercontent.com/assets/9845722/7402472/3534c48a-ee9a-11e4-9d38-c3e3b839ff6c.png)

My login to Salsa in general appears to be successful, as shown on the screen below. 
![screen shot 2015-04-29 at 6 05 40 pm](https://cloud.githubusercontent.com/assets/9845722/7402494/73eef06a-ee9a-11e4-9e5d-73af90643b52.png)

I tested the API as suggested in https://github.com/BusProject/SalsaPress/issues/27 using 
http://hq-salsa4.salsalabs.com/api/authenticate.sjs?email=david@birchstudio.com&password=***** and got the "Successful Login" message. 

I saw in another post a mention of form fields but since the page was working without them previously, I'm assuming they would be pulled in by the SalsaPress shortcode. 

Is there anything I'm missing on my end? 

Thanks in advance.

**Comment by mojowen** [comment]
Try debugging the form (and I'm doing this 100% from memory so - could be wrong):

http://hq-salsa4.salsalabs.com/api/getObject.sjs?object=signup_page&key=51327&json

**Comment by davidglenrobinson** [comment]
Hello. Thanks for the quick reply.  I tested the form in its native state on Salsa's URL at http://salsa4.salsalabs.com/o/51327/p/salsa/web/common/public/signup?signup_page_KEY=8567 and confirmed that it worked. 

![screen shot 2015-04-30 at 9 45 37 am](https://cloud.githubusercontent.com/assets/9845722/7413980/b6586ad4-ef1d-11e4-85b1-a7802ab328a3.png)

Regards,

**Comment by mojowen** [comment]
yeah but what does the API request *about* the form tell you - that's what SalsaPress is using to create the form - what do you see when you hit: http://hq-salsa4.salsalabs.com/api/getObject.sjs?object=signup_page&key=51327&json

**Comment by davidglenrobinson** [comment]
I see: 
{}

**Comment by mojowen** [comment]
So something about the Salsa API is not working or has changed - you should
get in touch with them

--
Scott Riker Duncombe
*503.893.8626* || *Twitter <http://twitter.com/sduncombe> *|| *Github
<http://github.com/mojowen> *||* Portfolio <http://scottduncombe.com/>*

On Thu, Apr 30, 2015 at 6:53 AM, davidglenrobinson <notifications@github.com

**Comment by davidglenrobinson** [comment]
Okay. Would an API issue prevent SalsaPress from inserting form data? In the code above, I mentioned that it currently just puts in a graphic.

**Comment by mojowen** [comment]
The graphic is a just a placeholder to look good in the WordPress editor -
when you publish the page you'll see an actual form.

Have you tried publishing the page?

**Comment by davidglenrobinson** [comment]
I published the page and it showed the graphic. 

But... holy cow. It makes a difference if I insert the form in Visual versus Text view. Visual, good. Text, bad. It didn't occur to me to attempt the different view modes. 

Problem solved. Thanks again.
