### ISSUE TITLE
Missing submit button for adding forms to page

### ISSUE THREAD

**Issue by redearthdesign** [BusProject/SalsaPress#49]
Hello,
Very excited about getting started with this plugin - connecting Salsa and WordPress is an amazing help to so many non-profits using both tools.

I am running into the same issue as this person:
https://wordpress.org/support/topic/cannot-place-shortcodes-for-forms
but since the support page says not to post there, wanted to post it here.

When I open a page to edit and click the Salsa button, I do have forms to choose from, so the API is connected. When I choose a form, I don't have a button to save or submit.

The firebug console also shows this error after selecting the form:

SyntaxError: missing ) after argument list
var serial = JSON.stringify($('.picked').serializeArray())
in line 108, col 9 of:
/plugins/salsa-press/admin/salsapress_admin.js

In case it's not related to that error, are there any know plugin conflicts or anything that might prevent a submit button from showing? I'll be going through and deactivating plugins during off hours, but wanted to put this out there in case anyone has run into it too and knows how to fix it.

Thank you and best wishes!

**Comment by redearthdesign** [comment]
A follow-up. I tried commenting out that line and then the report insert button shows up at the bottom, but no other submit buttons.

Running WordPress 4.3.1

**Comment by mojowen** [comment]
001225d474e48772a26a2c634033123c98444f49 should ahve fixed

**Comment by redearthdesign** [comment]
Thank you - the javascript error is resolved.

However, still no submit button to insert a form into the post. There is the insert button at the bottom, but it only links to reports, so if that's the only button, it's not recognizing that I selected a form to insert and have no info in the report selecting.

**Comment by mojowen** [comment]
You need to select a petition, event, or signup form before you see the insert button

![image](https://cloud.githubusercontent.com/assets/700444/11067130/ec2b5b44-877f-11e5-9e8c-4aca38789bb9.png)
