### ISSUE TITLE
Work with Salsa Engage?

### ISSUE THREAD

**Issue by c-merrick** [BusProject/SalsaPress#55]
Hi! Does this plugin work with Salsa Engage? I'm setting up a client website, they use Salsa Engage, but Salsapress won't connect. I'm not sure if I'm using the right base URL, but what they have seems to be in the format clientname.salsa.org, not salsa.clientname.org. If I'm wasting my time because this only works with Salsa Classic, I'd sure like to know sooner than later. Many thanks!

**Comment by drywall** [comment]
Pretty sure this just works with Classic.

**Comment by craftee123** [comment]
The plugin isn't really needed with Engage because all of the "Activities" can be embedded with code provided. Just publish and there will be a section called "Widgets for External Webpages," and you should be all set.

**Comment by c-merrick** [comment]
@craftee123 Thanks -- I figured this might be a simpler way to do essentially that. Guess I'll stick with pasting in widget code.
@drywall -- thanks for the response, I think you're right.
