### ISSUE TITLE
Error loading Visual Tab of WP Editor

### ISSUE THREAD

**Issue by aaemnnosttv** [BusProject/SalsaPress#58]
Just found this error being triggered when trying to load the Visual tab of the WordPress editor on the Notifications tab of a GravityForms settings page.  Nothing about it is GravityForms specific so I imagine that it could be happening in other non-standard placements of the WP editor.

```
Uncaught ReferenceError: SalsaPressVars is not defined
editor_plugin.js?wp-mce-4401-20160726:60 
```

![image](https://cloud.githubusercontent.com/assets/1621608/20902897/ea16cac2-bb41-11e6-8dcc-1cfdf1ee0e90.png)

**Comment by mojowen** [comment]
Hmm - I'm not seeing that error in the regular WP Editor. 

But 4533e558143bb283f0a2da6e333f34b710f478fa and db331b9481820b94a46d6b1b0391ee1c5cf2b6b1 should help protect against that error in non-SalesPressVars loading editors

**Comment by aaemnnosttv** [comment]
That fixed it; thanks for the quick response!

Any plan to release a new version on wp.org soon? Looks like it hasn't been updated in more than a year.

**Comment by mojowen** [comment]
Great! And I'll push the current master with a version bump to wp.org tonight.
