### ISSUE TITLE
Forms not showing

### ISSUE THREAD

**Issue by soo7mi** [BusProject/SalsaPress#59]
Forms aren't showing upon embed using Add Salsa button.  Trying to embed Sign Up form, but also tested using Salsa Petition as well.  Using WP 4.7.3 and Salsa settings note a Successful Login.  Cleared cache and no change.

Instead salsaembed.png is showing. 

![screen shot 2017-03-09 at 4 38 02 pm](https://cloud.githubusercontent.com/assets/12757228/23777151/6f906ed0-04e7-11e7-9998-5f7352430f1f.png)

**Comment by mojowen** [comment]
Try adding the shortcode via the *text* vs *visual* and you should get the shortcode

![image](https://cloud.githubusercontent.com/assets/700444/23811085/4a5c9524-0589-11e7-9ff1-7490b8b36f9e.png)

Honestly I'd also look into other plugin options - this one isn't in active development and you might get more mileage out of these other options:

![image](https://cloud.githubusercontent.com/assets/700444/23811106/5dee68a6-0589-11e7-9598-ab3e16d63d2e.png)

**Comment by soo7mi** [comment]
I did try adding the shortcode via text vs visual, but to no avail.  Thanks.  Appreciate the response.

**Comment by mojowen** [comment]
sorry I couldn't help - maybe finally time to unlist from the plugin directory.
